# Generated by Django 3.2.7 on 2021-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='researchpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('publication', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('authors', models.CharField(max_length=200, null=True)),
                ('year', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
