# Generated by Django 3.2.7 on 2021-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_researchpaper_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
