# Generated by Django 3.2.7 on 2021-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_joinus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='data',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
